{% set name = "yamlns" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/yamlns-{{ version }}.tar.gz
  sha256: c3f892e6a4219b49580d477955e008e5c73cdcd561f0b110c6def34c39453741

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=20.4
  run:
    - python >={{ python_min }}
    - pytest
    - pyyaml >=5.3.1
    - setuptools >=20.4
    - pytest-cov

test:
  imports:
    - yamlns
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/GuifiBaix/python-yamlns
  summary: YAML serializable dictionary with dual item and attribute accessors
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
