{% set name = "yamlns" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/yamlns-{{ version }}.tar.gz
  sha256: c6869decfd520bf59ab35b3610e123b2aa7fbf403674d03e94bc40f484b178c4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=20.4
  run:
    - python >={{ python_min {{
    - pytest
    - pyyaml >=5.3.1
    - setuptools >=20.4

test:
  imports:
    - yamlns
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/GuifiBaix/python-yamlns
  summary: YAML serializable dictionary with dual item and attribute accessors
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
